name: ZITADEL CI/CD

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Versioning"

  release:
    uses: ./.github/workflows/release.yml
    permissions:
      packages: write
      contents: write
      issues: write
      pull-requests: write
    needs:
      - version
    if: ${{ github.event_name == 'workflow_dispatch' }}
    with:
      build_image_name: ${{ needs.container.outputs.build_image }}
      semantic_version: "23.0.7"
      image_name: "ghcr.io/zitadel/zitadel"
      google_image_name: "europe-docker.pkg.dev/zitadel-common/zitadel-repo/zitadel"
