name: CI 

on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  lint_test_build_push:
    uses: ./.github/workflows/lint_test_build_push.yml
    if: ${{ github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read
    with:
      go_version: "1.25"
      node_version: "22"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      NX_CLOUD_ACCESS_TOKEN_READONLY: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

  release:
    uses: ./.github/workflows/release.yml
    permissions:
      packages: write
      contents: write
      issues: write
      pull-requests: write
    secrets:
      GCR_JSON_KEY_BASE64: ${{ secrets.GCR_JSON_KEY_BASE64 }}
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs:
      - lint_test_build_push
    with:
      go_version: "1.25"
      node_version: "22"
      semantic_version: "23.0.7"
      image_name_github_api: "ghcr.io/eliobischof/zitadel"
      image_name_google_api: "europe-docker.pkg.dev/zitadel-common/zitadel-repo/zitadel"
      image_name_github_login: "ghcr.io/eliobischof/zitadel-login"
      image_name_google_login: "europe-docker.pkg.dev/zitadel-common/zitadel-repo/zitadel-login"
