name: Package und Publish Archives and Images

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      image_name_github_api:
        required: true
        type: string
      image_name_github_login:
        required: true
        type: string
      image_name_google_api:
        required: true
        type: string
      image_name_google_login:
        required: true
        type: string
      semantic_version:
        required: false
        type: string
    secrets:
      GCR_JSON_KEY_BASE64:
        description: 'base64 endcrypted key to connect to Google'
        required: true

env:
  default_labels: |
    org.opencontainers.image.documentation=https://zitadel.com/docs
    org.opencontainers.image.vendor=ZITADEL

jobs:
  version:
    uses: ./.github/workflows/version.yml
    permissions:
      contents: write
    with:
      semantic_version: ${{ inputs.semantic_version }}
      dry_run: true

  pack:
    runs-on: ubuntu-22.04
    environment: ${{ github.ref_protected == 'true' && 'Protected' || null }}
    needs: version
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: "pnpm"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.28.0
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Pack API and Login
        env:
          ZITADEL_VERSION: ${{ needs.version.outputs.version }}
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN || secrets.NX_CLOUD_ACCESS_TOKEN_READONLY }}
        run: pnpm nx run --nxBail pack
      - name: Suggest Pipeline Fix By Nx Cloud AI
        if: always()
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN || secrets.NX_CLOUD_ACCESS_TOKEN_READONLY }}
        run: pnpm nx fix-ci
      - name: Upload all platform archives
        uses: actions/upload-artifact@v4
        with:
          name: zitadel-archives
          path: .artifacts/pack
