name: Release

on:
  workflow_call:
    inputs:
      semantic_version:
        required: true
        type: string
      build_image_name:
        required: true
        type: string
      image_name:
        required: true
        type: string
      google_image_name:
        required: true
        type: string

jobs:
  version:
    uses: ./.github/workflows/version.yml
    with:
      semantic_version: ${{ inputs.semantic_version }}
      dry_run: false
  publish:
    runs-on: ubuntu-latest
    needs:
      - version
    steps:
    - id: get_release
      uses: cardinalby/git-get-release-action@v1
      with:
        tag: ${{ needs.version.outputs.version }}
        draft: true
    - uses: eregon/publish-release@v1
      with:
        release_id: ${{ steps.get_release.outputs.id }}