name: Release

on:
  workflow_call:
    inputs:
      semantic_version:
        required: true
        type: string
      build_image_name:
        required: true
        type: string
      image_name:
        required: true
        type: string
      google_image_name:
        required: true
        type: string

jobs:
  version:
    uses: ./.github/workflows/version.yml
    with:
      semantic_version: ${{ inputs.semantic_version }}
      dry_run: false

